telegraf_output: "{{ telegraf.output | default('mon01.mydomain') }}"
telegraf_mysql_login: "{{ telegraf.mysql_login | default('root') }}"
telegraf_mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64656431306637616139303733623365393737353564316162376464663036653633393161333764
          3739633130373433386565386362343935373434336131380a616433343461633036666638316434
          30663230643439623237666534656139666337646537613332396133393562623633393330316631
          6465346230393933380a393536653366343432343037643737613161633532363734396661626564
          6435
