# Buckup node
target: instance-02

# vars for DB cluster (galera)
cluster:
  name: node1
  address:
    node1: "instance-02"
    node2: "instance-03"
    node3: "instance-04"
  mariadb:
    root_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64656431306637616139303733623365393737353564316162376464663036653633393161333764
          3739633130373433386565386362343935373434336131380a616433343461633036666638316434
          30663230643439623237666534656139666337646537613332396133393562623633393330316631
          6465346230393933380a393536653366343432343037643737613161633532363734396661626564
          6435


# vars for MySQL (database and user names)
managemysql:
  db_name_sait: wordpress
  user_name_sait: wordpress
  #site_passwd1: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37313038613037303363336632353339363163396431326631353633616135343761373166333832
          3661663037623661336331393537373737363035663764660a353838356334336134323138336261
          64393930323437346531363535653862306563383537333438373739343435383834623137343337
          3363346163616533360a363634363635353932366635663864613738383433346463343566353833
          6265
  site_passwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31373461376637316434643436353661356663356364636666643037393337666264663534393039
          3861643666616662626431353365623839633431643239360a623762656466373739393063303638
          66346665623530363561653261386365663430333437653437366637333839623532396537396536
          3333623133353033360a336132323163636637376238396333616437333465613366313236376532
          3862
  mon_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63636265333335313032646436303130393561626363393233316662613762373736346130653034
          3934613536616432363331636661316330383330353865660a373031353963623936656561373064
          30326430366638333235633234346261303564363230373338336334656337646330386634366230
          3531366536663463620a653664666135366637373263343563616565323833633435383061363637
          3162
