# firewall settings
iptables:
  accept_ports:
    - {protocol: tcp, port: 80}
    - {protocol: tcp, port: 443}
    - {protocol: tcp, port: 9090}
    - {protocol: tcp, port: 9093}


# settings for certbot
certbot_create_standalone_stop_services:
  - nginx
certbot_create_if_missing: true
certbot_certs:
  - email: admin@mydomain
    domains:
      - grafana.mydomain


# settings for InfluxDB
influxdb:
  db_name: telegraf
  user_name: telegraf
  password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          37363063333339613130386162663932393039363439633062666238616339336531316561386666
          3664643063653537383464663332346561623762373030330a333736356465333664653438326638
          31396265333566386435353639323666343263353130333236653930363966343165366630383231
          3365633238326539390a633138343863626531373265333236323631653662366562393532386430
          3464
  admin_user: admin
  admin_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          33643832626164666330346536336330326264356365646561376362383332633032656234363636
          6264353761616132316333303832633135616235366562370a373634373838643061366331303135
          33383638303363356565303637623866633362333165656633386465663539626532623339336364
          3939393535663061620a366166336565653237343462663734613833333665313561613163383264
          3035
  influx_bin: /usr/bin/influx
